from django.urls import path

from . import views

app_name = "drill"

urlpatterns = [
    path(
        route="",
        view=views.DrillListView.as_view(),
        name="list"
    ),
    path(
        route="question/delete/<uuid:uuid>/",
        view=views.QuestionDeleteView.as_view(),
        name="delete"
    ),
    path(
        route="question/<uuid:uuid>/",
        view=views.QuestionDetailView.as_view(),
        name="detail"
    ),
    path(
        route="question/add/<str:tag>/",
        view=views.QuestionCreateView.as_view(),
        name="add_with_tag"
    ),
    path(
        route="question/add/",
        view=views.QuestionCreateView.as_view(),
        name="add"
    ),
    path(
        route="question/update/<uuid:uuid>/",
        view=views.QuestionUpdateView.as_view(),
        name="update"
    ),
    path(
        route="question/skip/<uuid:uuid>/",
        view=views.skip_question,
        name="skip"
    ),
    path(
        route="mutate_is_favorite/",
        view=views.is_favorite_mutate,
        name="is_favorite_mutate"
    ),
    path(
        route="search/",
        view=views.DrillSearchListView.as_view(),
        name="search"
    ),
    path(
        route="search_tags/",
        view=views.search_tags,
        name="search_tags"
    ),
    path(
        route="answer/<uuid:uuid>/",
        view=views.show_answer,
        name="answer"
    ),
    path(
        route="response/<uuid:uuid>/<str:response>/",
        view=views.record_response,
        name="record_response"
    ),
    path(
        route="study/random/",
        view=views.study_random,
        name="study_random"
    ),
    path(
        route="study/tag/<str:tag>/",
        view=views.study_tag,
        name="study_tag"
    ),
    path(
        route="get_pinned_tags",
        view=views.get_pinned_tags,
        name="get_pinned_tags"
    ),
    path(
        route="pin_tag",
        view=views.pin_tag,
        name="pin_tag"
    ),
]
