from django.urls import path

from . import views

app_name = "drill"

urlpatterns = [
    path(
        route="",
        view=views.DrillListView.as_view(),
        name="list"
    ),
    path(
        route="question/delete/<uuid:uuid>/",
        view=views.QuestionDeleteView.as_view(),
        name="delete"
    ),
    path(
        route="question/<uuid:uuid>/",
        view=views.QuestionDetailView.as_view(),
        name="detail"
    ),
    path(
        route="question/add/<str:tag>/",
        view=views.QuestionCreateView.as_view(),
        name="add_with_tag"
    ),
    path(
        route="question/add/",
        view=views.QuestionCreateView.as_view(),
        name="add"
    ),
    path(
        route="question/update/<uuid:uuid>/",
        view=views.QuestionUpdateView.as_view(),
        name="update"
    ),
    path(
        route="mutate_is_favorite/",
        view=views.is_favorite_mutate,
        name="is_favorite_mutate"
    ),
    path(
        route="response/<uuid:uuid>/<str:response>/",
        view=views.record_response,
        name="record_response"
    ),
    path(
        route="start_study_session/<str:session_type>",
        view=views.start_study_session,
        name="start_study_session"
    ),
    path(
        route="start_study_session/tag/<str:tag>",
        view=views.start_study_session_tag,
        name="start_study_session_tag"
    ),
    path(
        route="start_study_session/random/<str:count>",
        view=views.start_study_session_random,
        name="start_study_session_random"
    ),
    path(
        route="start_study_session/search/<str:search>",
        view=views.start_study_session_search,
        name="start_study_session_search"
    ),
    path(
        route="study",
        view=views.get_next_question,
        name="study"
    ),
    path(
        route="resume",
        view=views.get_current_question,
        name="resume"
    ),
    path(
        route="get_pinned_tags",
        view=views.get_pinned_tags,
        name="get_pinned_tags"
    ),
    path(
        route="pin_tag",
        view=views.pin_tag,
        name="pin_tag"
    ),
    path(
        route="unpin_tag",
        view=views.unpin_tag,
        name="unpin_tag"
    ),
    path(
        route="sort_pinned_tags",
        view=views.sort_pinned_tags,
        name="sort_pinned_tags"
    ),
    path(
        route="get_title_from_url",
        view=views.get_title_from_url,
        name="get_title_from_url"
    ),
    path(
        route="related_objects/<uuid:uuid>",
        view=views.get_related_objects,
        name="related_objects"
    ),
    path(
        route="related_objects/add",
        view=views.add_object,
        name="add_object"
    ),
    path(
        route="related_objects/remove_object",
        view=views.remove_object,
        name="remove_object"
    ),
    path(
        route="related_objects/edit_note",
        view=views.edit_related_object_note,
        name="edit_related_object_note"
    ),
]
