# Generated by Django 3.2.13 on 2022-07-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_quote_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
