# Generated by Django 2.2.10 on 2020-04-28 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_urgent',
        ),
    ]
