# Generated by Django 2.2.10 on 2020-04-30 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
