# Generated by Django 2.2.10 on 2020-05-12 20:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
