# Generated by Django 2.2.10 on 2020-05-25 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0006_tagalias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0005_todo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tag.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagTodoSortOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('tag_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.TagTodo')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Todo')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('tag_todo', 'todo')},
            },
        ),
        migrations.AddField(
            model_name='tagtodo',
            name='todos',
            field=models.ManyToManyField(through='todo.TagTodoSortOrder', to='todo.Todo'),
        ),
        migrations.AddField(
            model_name='tagtodo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
