# Generated by Django 2.2.13 on 2020-10-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200525_1714'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagtodosortorder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tagtodosortorder',
            name='tag_todo',
        ),
        migrations.RemoveField(
            model_name='tagtodosortorder',
            name='todo',
        ),
        migrations.DeleteModel(
            name='TagTodo',
        ),
        migrations.DeleteModel(
            name='TagTodoSortOrder',
        ),
    ]
