# Generated by Django 2.2.13 on 2021-02-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20201027_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
