# Generated by Django 2.2.13 on 2021-04-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_remove_todo_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='name',
        ),
    ]
