# Generated by Django 3.2.4 on 2021-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20210414_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
