# Generated by Django 2.0.7 on 2019-02-18 23:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookmarkTagUser',
            new_name='TagBookmarkList',
        ),
    ]
