# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-28 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='importance',
            field=models.IntegerField(default=1),
        ),
    ]
