# Generated by Django 2.0.7 on 2019-04-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20190218_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagbookmarklist',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagbookmarklist',
            name='user',
        ),
        migrations.DeleteModel(
            name='TagBookmarkList',
        ),
    ]
