# Generated by Django 2.2.13 on 2020-11-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20190331_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
