# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 21:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='daily',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
