# Generated by Django 2.2.13 on 2021-02-06 00:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_auto_20201101_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
