# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 22:22
from __future__ import unicode_literals

import bookmark.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_bookmark_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='daily',
            field=bookmark.models.DailyBookmarkJSONField(blank=True, null=True),
        ),
    ]
