# Generated by Django 2.2.13 on 2021-02-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_bookmark_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
