# Generated by Django 2.2.13 on 2021-04-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0008_auto_20210221_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='title',
            new_name='name',
        ),
    ]
