# Generated by Django 3.2.5 on 2022-02-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0009_auto_20210414_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
