# Generated by Django 2.0.7 on 2018-09-23 21:10

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_feeds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('bookmarks_show_untagged_only', models.BooleanField(default=False)),
                ('orgmode_file', models.TextField()),
                ('google_calendar', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('favorite_tags', models.ManyToManyField(to='tag.Tag')),
                ('homepage_default_collection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_collection', to='collection.Collection')),
                ('todo_default_tag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_tag', to='tag.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
