# Generated by Django 2.2.13 on 2021-04-16 19:18

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0003_collection_uuid'),
        ('tag', '0013_auto_20210108_1637'),
        ('blob', '0001_initial'),
        ('feed', '0004_auto_20210212_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderDrillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='SortOrderUserFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='SortOrderUserNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.Blob')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='SortOrderUserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('orgmode_file', models.TextField(null=True)),
                ('google_calendar', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sidebar_image', models.TextField(blank=True, null=True)),
                ('theme', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=20)),
                ('feeds', models.ManyToManyField(through='accounts.SortOrderUserFeed', to='feed.Feed')),
                ('homepage_default_collection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_collection', to='collection.Collection')),
                ('pinned_drill_tags', models.ManyToManyField(related_name='pinned_drill_tags', through='accounts.SortOrderDrillTag', to='tag.Tag')),
                ('pinned_notes', models.ManyToManyField(through='accounts.SortOrderUserNote', to='blob.Blob')),
                ('pinned_tags', models.ManyToManyField(through='accounts.SortOrderUserTag', to='tag.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sortorderusertag',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='sortorderusernote',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='sortorderuserfeed',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='sortorderdrilltag',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='sortorderusertag',
            unique_together={('userprofile', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='sortorderusernote',
            unique_together={('userprofile', 'note')},
        ),
        migrations.AlterUniqueTogether(
            name='sortorderuserfeed',
            unique_together={('userprofile', 'feed')},
        ),
        migrations.AlterUniqueTogether(
            name='sortorderdrilltag',
            unique_together={('userprofile', 'tag')},
        ),
    ]
