# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 20:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0002_auto_20150705_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_feeds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('bookmarks_show_untagged_only', models.BooleanField(default=False)),
                ('orgmode_file', models.TextField()),
                ('google_calendar', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('favorite_tags', models.ManyToManyField(to='tag.Tag')),
                ('todo_default_tag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_tag', to='tag.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
