# Generated by Django 3.2.4 on 2021-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='google_calendar',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
