# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collection_description'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='homepage_default_collection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_collection', to='collection.Collection'),
        ),
    ]
