# Generated by Django 2.0.7 on 2018-10-13 21:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_tags',
            field=models.ManyToManyField(null=True, to='tag.Tag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='orgmode_file',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rss_feeds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
