# Generated by Django 3.2.5 on 2021-11-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_google_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
