# Generated by Django 2.0.7 on 2019-01-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181013_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_tags',
        ),
    ]
