# Generated by Django 2.2.13 on 2020-11-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sidebar_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
