# Generated by Django 2.0.7 on 2019-01-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('accounts', '0003_remove_userprofile_favorite_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_tags',
            field=models.ManyToManyField(through='accounts.SortOrder', to='tag.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='sortorder',
            unique_together={('user_profile', 'tag', 'sort_order')},
        ),
    ]
