# Generated by Django 2.2.13 on 2021-01-23 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_sidebar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='todo_default_tag',
        ),
    ]
