# Generated by Django 3.2.5 on 2022-01-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_instagram_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nytimes_api_token',
            field=models.TextField(null=True),
        ),
    ]
