# Generated by Django 2.2.13 on 2021-02-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feed_user'),
        ('accounts', '0004_remove_userprofile_todo_default_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderUserFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('userprofile', 'feed')},
            },
        ),
    ]
