# Generated by Django 2.0.7 on 2019-01-21 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('accounts', '0004_auto_20190106_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortorder',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterUniqueTogether(
            name='sortorder',
            unique_together={('user_profile', 'tag')},
        ),
    ]
