# Generated by Django 3.2.5 on 2022-01-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_nytimes_api_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nytimes_api_token',
            new_name='nytimes_api_key',
        ),
    ]
