# Generated by Django 2.2.13 on 2021-02-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feed_user'),
        ('accounts', '0005_sortorderuserfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='feeds',
            field=models.ManyToManyField(through='accounts.SortOrderUserFeed', to='feed.Feed'),
        ),
    ]
