# Generated by Django 3.2.5 on 2022-03-14 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_alter_collection_description'),
        ('accounts', '0005_rename_nytimes_api_token_userprofile_nytimes_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='homepage_image_collection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_collection', to='collection.collection'),
        ),
    ]
