# Generated by Django 2.0.7 on 2019-04-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190120_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bookmarks_show_untagged_only',
        ),
    ]
