# Generated by Django 2.2.10 on 2020-05-02 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0001_initial'),
        ('accounts', '0006_remove_userprofile_bookmarks_show_untagged_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.Document')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('user_profile', 'note')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_notes',
            field=models.ManyToManyField(through='accounts.SortOrderNote', to='blob.Document'),
        ),
    ]
