# Generated by Django 3.2.5 on 2022-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_homepage_image_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='orgmode_file',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
