# Generated by Django 2.2.13 on 2021-02-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_feeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rss_feeds',
        ),
    ]
