# Generated by Django 2.2.10 on 2020-06-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200502_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('flatly', 'flatly'), ('darkly', 'darkly'), ('cerulean', 'cerulean'), ('slate', 'slate')], default='flatly', max_length=20),
        ),
    ]
