# Generated by Django 3.2.15 on 2022-09-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220504_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark'), ('purple', 'purple')], default='light', max_length=20),
        ),
    ]
