# Generated by Django 2.2.13 on 2021-03-06 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0013_auto_20210108_1637'),
        ('accounts', '0007_remove_userprofile_rss_feeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderDrillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('userprofile', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_drill_tags',
            field=models.ManyToManyField(related_name='favorite_drill_tags', through='accounts.SortOrderDrillTag', to='tag.Tag'),
        ),
    ]
