# Generated by Django 2.2.13 on 2020-08-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('cerulean', 'cerulean'), ('cosmo', 'cosmo'), ('darkly', 'darkly'), ('flatly', 'flatly'), ('journal', 'journal'), ('litera', 'litera'), ('minty', 'minty'), ('pulse', 'pulse'), ('slate', 'slate'), ('sandstone', 'sandstone'), ('simplex', 'simplex'), ('solar', 'solar'), ('spacelab', 'spacelab'), ('superhero', 'superhero'), ('united', 'united'), ('yeti', 'yeti')], default='flatly', max_length=20),
        ),
    ]
