# Generated by Django 3.2.15 on 2022-10-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0017_rename_sortordertagtodo_tagtodo'),
        ('accounts', '0008_alter_userprofile_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortOrderUserTag',
            new_name='UserTag',
        ),
    ]
