# Generated by Django 2.2.13 on 2021-03-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210306_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_notes',
            new_name='pinned_notes',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_tags',
            new_name='pinned_tags',
        ),
    ]
