# Generated by Django 3.2.15 on 2022-10-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0020_remove_bcobject_question'),
        ('accounts', '0009_rename_sortorderusertag_usertag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortOrderUserNote',
            new_name='UserNote',
        ),
    ]
