# Generated by Django 2.2.13 on 2020-10-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200829_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=20),
        ),
    ]
