# Generated by Django 3.2.15 on 2022-10-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210212_1924'),
        ('accounts', '0010_rename_sortorderusernote_usernote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortOrderUserFeed',
            new_name='UserFeed',
        ),
    ]
