# Generated by Django 2.2.13 on 2020-10-28 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0011_auto_20201028_1301'),
        ('accounts', '0010_auto_20201026_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderUserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('user_profile', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_tags_new',
            field=models.ManyToManyField(related_name='_userprofile_favorite_tags_new_+', through='accounts.SortOrderUserTag', to='tag.Tag'),
        ),
    ]
