# Generated by Django 2.2.13 on 2020-10-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0011_auto_20201028_1301'),
        ('accounts', '0011_auto_20201028_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortorderusertag',
            old_name='user_profile',
            new_name='userprofile',
        ),
        migrations.AlterUniqueTogether(
            name='sortorderusertag',
            unique_together={('userprofile', 'tag')},
        ),
    ]
