# Generated by Django 3.2.15 on 2022-10-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0017_rename_sortordertagtodo_tagtodo'),
        ('accounts', '0011_rename_sortorderuserfeed_userfeed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortOrderDrillTag',
            new_name='DrillTag',
        ),
    ]
