# Generated by Django 2.2.13 on 2020-10-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201028_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_tags',
        ),
        migrations.DeleteModel(
            name='SortOrder',
        ),
    ]
