# Generated by Django 3.2.18 on 2023-04-25 22:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_sortorderdrilltag_drilltag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='drill_intervals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[1, 2, 3, 5, 8, 13, 21, 30]), default=[1, 2, 3, 5, 8, 13, 21, 30], size=None),
            preserve_default=False,
        ),
    ]
