# Generated by Django 3.2.24 on 2024-02-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_drill_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='eye_candy',
            field=models.BooleanField(default=False),
        ),
    ]
