# Generated by Django 2.2.13 on 2020-10-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0011_auto_20201028_1301'),
        ('accounts', '0013_auto_20201028_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_tags_new',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_tags',
            field=models.ManyToManyField(related_name='_userprofile_favorite_tags_+', through='accounts.SortOrderUserTag', to='tag.Tag'),
        ),
    ]
