# Generated by Django 4.2.21 on 2025-05-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0018_tag_check_name_is_lowercase"),
        ("accounts", "0014_userprofile_eye_candy"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="drill_tags_muted",
            field=models.ManyToManyField(related_name="drill_tags_muted", to="tag.tag"),
        ),
    ]
