# Generated by Django 2.2.13 on 2020-10-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201028_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_tags',
            field=models.ManyToManyField(through='accounts.SortOrderUserTag', to='tag.Tag'),
        ),
    ]
