# Generated by Django 2.2.13 on 2020-10-28 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
#        ('blob', '0003_auto_20200519_1821'),
        ('accounts', '0015_auto_20201028_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderUserNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.Blob')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('userprofile', 'note')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_notes_new',
            field=models.ManyToManyField(related_name='_userprofile_favorite_notes_new_+', through='accounts.SortOrderUserNote', to='blob.Blob'),
        ),
    ]
