# Generated by Django 4.2.22 on 2025-07-27 16:56

import accounts.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_userprofile_drill_tags_muted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="drill_intervals",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                default=accounts.models.drill_intervals_default,
                size=None,
            ),
        ),
    ]
