# Generated by Django 2.2.13 on 2020-10-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201028_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_notes',
        ),
        migrations.DeleteModel(
            name='SortOrderNote',
        ),
    ]
