# Generated by Django 4.2.22 on 2025-07-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_userprofile_drill_intervals"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="google_calendar_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
