# Generated by Django 2.2.13 on 2020-10-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0003_auto_20200519_1821'),
        ('accounts', '0017_auto_20201028_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_notes_new',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_notes',
            field=models.ManyToManyField(through='accounts.SortOrderUserNote', to='blob.Blob'),
        ),
    ]
