# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='importance',
            field=models.IntegerField(default=1),
        ),
    ]
