from django.urls import path

from . import views

app_name = "blob"

urlpatterns = [
    path(
        route="list",
        view=views.BlobListView.as_view(),
        name="list"
    ),
    path(
        route="<uuid:uuid>/",
        view=views.BlobDetailView.as_view(),
        name="detail"
    ),
    path(
        route="<uuid:uuid>/update/",
        view=views.BlobUpdateView.as_view(),
        name="update"
    ),
    path(
        route="create/",
        view=views.BlobCreateView.as_view(),
        name="create"
    ),
    path(
        route="<uuid:uuid>/delete/",
        view=views.BlobDeleteView.as_view(),
        name="delete"
    ),
    path(
        route="metadata_name_search/",
        view=views.metadata_name_search,
        name="metadata_name_search"
    ),
    path(
        route="mutate/",
        view=views.collection_mutate,
        name="collection_mutate"
    ),
    path(
        route="parse_date/<path:input_date>/",
        view=views.parse_date,
        name="parse_date"
    ),
    path(
        route="recent_blobs",
        view=views.recent_blobs,
        name="recent_blobs"
    ),
    path(
        route="elasticsearch_info/<uuid:uuid>",
        view=views.get_elasticsearch_info,
        name="get_elasticsearch_info"
    ),
    path(
        route="clone/<uuid:uuid>",
        view=views.BlobCloneView.as_view(),
        name="clone"
    ),
    path(
        route="import",
        view=views.BlobImportView.as_view(),
        name="import"
    ),
    path(
        route="related_blobs/<uuid:uuid>",
        view=views.get_related_blobs,
        name="related_blobs"
    ),
    path(
        route="link",
        view=views.link,
        name="link"
    ),
    path(
        route="unlink",
        view=views.unlink,
        name="unlink"
    ),
    path(
        route="<uuid:uuid>/bookmark_list",
        view=views.get_bookmark_list,
        name="get_bookmark_list"
    ),
    path(
        route="blob/sort",
        view=views.sort_bookmark_list,
        name="sort_bookmark_list"
    ),
    path(
        route="blob/add_bookmark",
        view=views.add_bookmark,
        name="add_bookmark"
    ),
    path(
        route="bookmark/remove",
        view=views.remove_bookmark,
        name="remove_bookmark"
    ),
    path(
        route="bookmark/edit_note",
        view=views.edit_bookmark_note,
        name="edit_bookmark_note"
    ),
]
