from django.urls import path

from . import views

app_name = "blob"

urlpatterns = [
    path(
        route="list",
        view=views.BlobListView.as_view(),
        name="list"
    ),
    path(
        route="<uuid:uuid>/",
        view=views.BlobDetailView.as_view(),
        name="detail"
    ),
    path(
        route="<uuid:uuid>/update/",
        view=views.BlobUpdateView.as_view(),
        name="update"
    ),
    path(
        route="create/",
        view=views.BlobCreateView.as_view(),
        name="create"
    ),
    path(
        route="metadata_name_search/",
        view=views.metadata_name_search,
        name="metadata_name_search"
    ),
    path(
        route="parse_date/<path:input_date>/",
        view=views.parse_date,
        name="parse_date"
    ),
    path(
        route="update_cover_image",
        view=views.update_cover_image,
        name="update_cover_image"
    ),
    path(
        route="elasticsearch_info/<uuid:uuid>",
        view=views.get_elasticsearch_info,
        name="get_elasticsearch_info"
    ),
    path(
        route="clone/<uuid:uuid>",
        view=views.BlobCloneView.as_view(),
        name="clone"
    ),
    path(
        route="import",
        view=views.BlobImportView.as_view(),
        name="import"
    ),
    path(
        route="related_blobs/<uuid:uuid>",
        view=views.get_related_blobs,
        name="related_blobs"
    ),
    path(
        route="link",
        view=views.link,
        name="link"
    ),
    path(
        route="unlink",
        view=views.unlink,
        name="unlink"
    ),
    path(
        route="update_page_number",
        view=views.update_page_number,
        name="update_page_number"
    ),
    path(
        route="related_blob/note/update",
        view=views.update_related_blob_note,
        name="update_related_blob_note"
    ),
]
