# Generated by Django 2.0.7 on 2018-10-13 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0001_squashed_0009_auto_20181006_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='efactor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
