# Generated by Django 2.2.10 on 2020-03-30 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0002_auto_20181013_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='interval_new',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
