# Generated by Django 2.2.10 on 2020-03-30 00:51

from datetime import timedelta

from django.db import migrations


def transfer_interval(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Question = apps.get_model("drill", "Question")
    for question in Question.objects.all():
        question.interval_new = timedelta(days=question.interval)
        question.save()


class Migration(migrations.Migration):

    dependencies = [
        ("drill", "0003_question_interval_new"),
    ]

    operations = [
        migrations.RunPython(transfer_interval),
    ]
