# Generated by Django 2.2.10 on 2020-03-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0004_auto_20200329_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='interval',
        ),
    ]
