# Generated by Django 2.2.10 on 2020-03-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0005_remove_question_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='interval_new',
            new_name='interval',
        ),
    ]
