# Generated by Django 2.2.10 on 2020-04-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0006_auto_20200330_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='deck',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
