# Generated by Django 2.2.13 on 2021-03-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0008_question_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('L', 'Learning'), ('R', 'Reviewing')], default='L', max_length=1),
        ),
    ]
