# Generated by Django 2.2.13 on 2021-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0009_auto_20210306_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
