# Generated by Django 2.2.22 on 2021-05-25 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0009_auto_20210414_1951'),
        ('drill', '0010_question_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderDrillBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark.Bookmark')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.Question')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('question', 'bookmark')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='bookmarks',
            field=models.ManyToManyField(through='drill.SortOrderDrillBookmark', to='bookmark.Bookmark'),
        ),
    ]
