# Generated by Django 3.2.5 on 2021-09-21 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0003_auto_20210715_2017'),
        ('drill', '0011_auto_20210525_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderDrillBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.blob')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.question')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('question', 'blob')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='blobs',
            field=models.ManyToManyField(through='drill.SortOrderDrillBlob', to='blob.Blob'),
        ),
    ]
