# Generated by Django 3.2.5 on 2022-01-21 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0009_auto_20210414_1951'),
        ('drill', '0013_questionresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortOrderDrillBookmark',
            new_name='SortOrderQuestionBookmark',
        ),
    ]
