# Generated by Django 3.2.5 on 2022-02-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0008_auto_20220108_1715'),
        ('drill', '0014_rename_sortorderdrillbookmark_sortorderquestionbookmark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortOrderDrillBlob',
            new_name='SortOrderQuestionBlob',
        ),
    ]
