# Generated by Django 3.2.15 on 2022-10-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0017_bcobject'),
        ('drill', '0015_rename_sortorderdrillblob_sortorderquestionblob'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bc_objects',
            field=models.ManyToManyField(blank=True, related_name='bc_object', to='blob.BCObject'),
        ),
    ]
