# Generated by Django 3.2.15 on 2022-10-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0016_question_bc_objects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sortorderquestionbookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sortorderquestionbookmark',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='sortorderquestionbookmark',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='blobs',
        ),
        migrations.RemoveField(
            model_name='question',
            name='bookmarks',
        ),
        migrations.DeleteModel(
            name='SortOrderQuestionBlob',
        ),
        migrations.DeleteModel(
            name='SortOrderQuestionBookmark',
        ),
    ]
