# Generated by Django 3.2.16 on 2022-11-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0020_remove_bcobject_question'),
        ('drill', '0017_auto_20221019_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='bc_objects',
            field=models.ManyToManyField(blank=True, related_name='bc_objects', to='blob.BCObject'),
        ),
    ]
