# Generated by Django 3.2.16 on 2022-11-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0018_alter_question_bc_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='interval_index',
            field=models.IntegerField(default=1),
        ),
    ]
