# Generated by Django 3.2.16 on 2022-11-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0019_question_interval_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='interval_index',
            field=models.IntegerField(default=0),
        ),
    ]
