# Generated by Django 3.2.16 on 2022-11-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0020_alter_question_interval_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='efactor',
        ),
        migrations.RemoveField(
            model_name='question',
            name='learning_step',
        ),
        migrations.RemoveField(
            model_name='question',
            name='state',
        ),
    ]
