# Generated by Django 3.2.18 on 2023-03-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0021_auto_20221107_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='bc_objects',
            new_name='bc_objects_old',
        ),
    ]
