# Generated by Django 3.2.18 on 2023-03-21 23:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0026_alter_blobtoobject_unique_together'),
        ('bookmark', '0010_bookmark_data'),
        ('drill', '0022_rename_bc_objects_question_bc_objects_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionToObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('bc_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.bcobject')),
                ('blob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blob.blob')),
                ('bookmark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmark.bookmark')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='drill.question')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.question')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('node', 'question'), ('node', 'blob'), ('node', 'bookmark')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='bc_objects',
            field=models.ManyToManyField(through='drill.QuestionToObject', to='drill.BCObject'),
        ),
    ]
