# Generated by Django 3.2.18 on 2023-03-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0023_auto_20230321_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bc_objects_old',
        ),
    ]
