# Generated by Django 3.2.19 on 2023-06-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0024_remove_question_bc_objects_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reversible',
            field=models.BooleanField(default=False),
        ),
    ]
