# Generated by Django 3.2.19 on 2023-06-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0025_question_reversible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='reversible',
            new_name='is_reversible',
        ),
    ]
