# Generated by Django 3.2.19 on 2023-07-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0026_rename_reversible_question_is_reversible'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
