# Generated by Django 4.2.22 on 2025-09-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drill", "0027_question_is_disabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="interval_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="times_failed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
