# Generated by Django 5.2.6 on 2025-09-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drill", "0028_alter_question_interval_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="bc_objects",
            field=models.ManyToManyField(
                through="drill.QuestionToObject",
                through_fields=("node", "bc_object"),
                to="drill.bcobject",
            ),
        ),
    ]
