# Generated by Django 2.2.13 on 2021-04-16 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookmark', '0009_auto_20210414_1951'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SortOrderNodeBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark.Bookmark')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.Node')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('node', 'bookmark')},
            },
        ),
        migrations.CreateModel(
            name='SortOrderNodeBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.Blob')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.Node')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('node', 'blob')},
            },
        ),
        migrations.AddField(
            model_name='node',
            name='blobs',
            field=models.ManyToManyField(through='node.SortOrderNodeBlob', to='blob.Blob'),
        ),
        migrations.AddField(
            model_name='node',
            name='bookmarks',
            field=models.ManyToManyField(through='node.SortOrderNodeBookmark', to='bookmark.Bookmark'),
        ),
        migrations.AddField(
            model_name='node',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
