# Generated by Django 2.2.13 on 2020-09-05 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0003_auto_20200519_1821'),
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderNodeBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.Blob')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='node',
            name='blobs',
            field=models.ManyToManyField(through='node.SortOrderNodeBlob', to='blob.Blob'),
        ),
    ]
