# Generated by Django 3.2.5 on 2022-05-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20210523_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='layout',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
