# Generated by Django 2.2.13 on 2020-09-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20200905_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortordernodeblob',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterModelOptions(
            name='sortordernodebookmark',
            options={'ordering': ('sort_order',)},
        ),
    ]
