# Generated by Django 3.2.5 on 2022-05-11 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_todo_due_date'),
        ('node', '0003_node_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='layout',
            field=models.JSONField(blank=True, default=[[{'type': 'blob'}], [{'type': 'bookmark'}], [{'type': 'note'}]], null=True),
        ),
        migrations.CreateModel(
            name='SortOrderNodeTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.node')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todo')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('node', 'todo')},
            },
        ),
    ]
