# Generated by Django 2.2.13 on 2020-09-05 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20190331_2024'),
        ('blob', '0003_auto_20200519_1821'),
        ('node', '0003_auto_20200905_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortordernodeblob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sortordernodebookmark',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='sortordernodeblob',
            unique_together={('node', 'blob')},
        ),
        migrations.AlterUniqueTogether(
            name='sortordernodebookmark',
            unique_together={('node', 'bookmark')},
        ),
    ]
