# Generated by Django 3.2.5 on 2022-05-25 00:21

from django.db import migrations, models
import node.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_todo_due_date'),
        ('node', '0004_auto_20220510_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='todos',
            field=models.ManyToManyField(through='node.SortOrderNodeTodo', to='todo.Todo'),
        ),
        migrations.AlterField(
            model_name='node',
            name='layout',
            field=models.JSONField(blank=True, default=node.models.default_layout, null=True),
        ),
    ]
