# Generated by Django 2.2.13 on 2020-09-07 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_auto_20200905_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
