# Generated by Django 3.2.13 on 2022-05-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_auto_20220524_2051'),
        ('node', '0005_auto_20220524_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='collections',
            field=models.ManyToManyField(to='collection.Collection'),
        ),
    ]
