# Generated by Django 2.2.13 on 2020-10-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_node_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortordernodeblob',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterModelOptions(
            name='sortordernodebookmark',
            options={'ordering': ('sort_order',)},
        ),
    ]
