# Generated by Django 3.2.13 on 2022-05-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_node_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='collections',
        ),
    ]
