# Generated by Django 3.2.13 on 2022-05-31 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_remove_node_collections'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sortordernodebookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sortordernodebookmark',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='sortordernodebookmark',
            name='node',
        ),
        migrations.RemoveField(
            model_name='node',
            name='blobs',
        ),
        migrations.RemoveField(
            model_name='node',
            name='bookmarks',
        ),
        migrations.DeleteModel(
            name='SortOrderNodeBlob',
        ),
        migrations.DeleteModel(
            name='SortOrderNodeBookmark',
        ),
    ]
