# Generated by Django 3.2.15 on 2022-10-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_todo_priority'),
        ('node', '0008_auto_20220531_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortOrderNodeTodo',
            new_name='NodeTodo',
        ),
    ]
