# Generated by Django 5.2.6 on 2025-09-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0009_rename_sortordernodetodo_nodetodo"),
        ("todo", "0015_alter_todo_priority"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nodetodo",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="nodetodo",
            constraint=models.UniqueConstraint(
                fields=("node", "todo"), name="uniq_node_todo"
            ),
        ),
    ]
