# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20150705_1440'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
