# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collection_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
