# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
