# Generated by Django 3.2.4 on 2021-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collection_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='blob_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
