# Generated by Django 3.2.5 on 2021-07-16 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0003_auto_20210715_2017'),
        ('collection', '0004_alter_collection_blob_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderCollectionBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.blob')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('collection', 'blob')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='blobs',
            field=models.ManyToManyField(through='collection.SortOrderCollectionBlob', to='blob.Blob'),
        ),
    ]
