# Generated by Django 3.2.5 on 2021-07-16 19:16

from django.db import migrations

from blob.models import Blob
from collection.models import Collection, SortOrderCollectionBlob


def add_blob_list(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    for collection in Collection.objects.all().exclude(uuid="b5153790-5e16-4c2d-924c-04010a3f4f98"):
        if collection.blob_list:
            for blob in collection.blob_list[::-1]:
                blob = Blob.objects.get(id=blob["id"])
                print(blob.name)
                so = SortOrderCollectionBlob(collection=collection, blob=blob)
                so.save()


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20210715_2017'),
    ]

    operations = [
        migrations.RunPython(add_blob_list),
    ]
