# Generated by Django 3.2.5 on 2021-07-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20210716_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='blob_list',
        ),
    ]
