# Generated by Django 3.2.5 on 2021-12-17 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_remove_collection_blob_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortordercollectionblob',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
