# Generated by Django 3.2.5 on 2021-12-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_sortordercollectionblob_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
