# Generated by Django 3.2.5 on 2021-12-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_alter_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
