# Generated by Django 3.2.5 on 2022-05-25 00:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_bookmark_data'),
        ('blob', '0011_alter_blob_math_support'),
        ('collection', '0010_alter_collection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('blob_uuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blob.blob')),
                ('bookmark_uuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookmark.bookmark')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SortOrderCollectionObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.object')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('collection', 'object')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='objects',
            field=models.ManyToManyField(through='collection.SortOrderCollectionObject', to='collection.Object'),
        ),
    ]
