# Generated by Django 3.2.5 on 2022-05-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_bookmark_data'),
        ('blob', '0011_alter_blob_math_support'),
        ('collection', '0011_auto_20220524_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='BCObject',
        ),
        migrations.RenameModel(
            old_name='SortOrderCollectionObject',
            new_name='SortOrderCollectionBCObject',
        ),
    ]
