# Generated by Django 3.2.5 on 2022-05-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_auto_20220524_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bcobject',
            old_name='blob_uuid',
            new_name='blob',
        ),
        migrations.RenameField(
            model_name='bcobject',
            old_name='bookmark_uuid',
            new_name='bookmark',
        ),
    ]
