# Generated by Django 3.2.5 on 2022-05-25 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_bookmark_data'),
        ('blob', '0011_alter_blob_math_support'),
        ('collection', '0013_auto_20220524_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcobject',
            name='blob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blob.blob'),
        ),
        migrations.AlterField(
            model_name='bcobject',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookmark.bookmark'),
        ),
    ]
