# Generated by Django 3.2.13 on 2022-05-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0011_alter_blob_math_support'),
        ('bookmark', '0010_bookmark_data'),
        ('collection', '0014_auto_20220524_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortordercollectionbcobject',
            name='blob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blob.blob'),
        ),
        migrations.AddField(
            model_name='sortordercollectionbcobject',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookmark.bookmark'),
        ),
    ]
