# Generated by Django 3.2.13 on 2022-05-29 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_auto_20220529_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortordercollectionbcobject',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.bcobject'),
        ),
    ]
