# Generated by Django 3.2.13 on 2022-05-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0011_alter_blob_math_support'),
        ('bookmark', '0010_bookmark_data'),
        ('collection', '0016_alter_sortordercollectionbcobject_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcobject',
            name='blob',
        ),
        migrations.RemoveField(
            model_name='bcobject',
            name='bookmark',
        ),
        migrations.AlterUniqueTogether(
            name='sortordercollectionbcobject',
            unique_together={('collection', 'blob', 'bookmark')},
        ),
    ]
