# Generated by Django 3.2.13 on 2022-05-30 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_bookmark_data'),
        ('blob', '0011_alter_blob_math_support'),
        ('collection', '0017_auto_20220529_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortordercollectionbcobject',
            name='blob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blob.blob'),
        ),
        migrations.AlterField(
            model_name='sortordercollectionbcobject',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmark.bookmark'),
        ),
    ]
