# Generated by Django 3.2.13 on 2022-06-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_delete_sortordercollectionblob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='objects',
            new_name='bc_objects',
        ),
    ]
