# Generated by Django 3.2.13 on 2022-06-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_bookmark_data'),
        ('blob', '0011_alter_blob_math_support'),
        ('collection', '0021_rename_objects_collection_bc_objects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortOrderCollectionBCObject',
            new_name='CollectionObject',
        ),
    ]
