# Generated by Django 3.2.15 on 2022-10-07 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0015_rename_sortorderdrillblob_sortorderquestionblob'),
        ('collection', '0022_rename_sortordercollectionbcobject_collectionobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionobject',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.question'),
        ),
        migrations.AlterField(
            model_name='collectionobject',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
    ]
