# Generated by Django 3.2.15 on 2022-10-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0023_auto_20221006_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionobject',
            name='question',
        ),
    ]
