# Generated by Django 3.2.18 on 2023-03-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0024_remove_collectionobject_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='is_private',
            new_name='is_favorite',
        ),
    ]
