# Generated by Django 2.2.13 on 2021-01-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetricData',
        ),
    ]
