# Generated by Django 3.2.4 on 2021-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_metricdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricdata',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
