# Generated by Django 3.2.5 on 2022-05-05 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_metricdata_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='frequency',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
