# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 23:40
from __future__ import unicode_literals

import blob.amazon
import blob.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0002_auto_20150705_1440'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sha1sum', models.CharField(max_length=40, unique=True)),
                ('filename', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('blobs', models.ManyToManyField(related_name='_blob_blobs_+', to='blob.Blob')),
                ('tags', models.ManyToManyField(to='tag.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(models.Model, blob.amazon.AmazonMixin),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('sha1sum', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('file', models.FileField(max_length=500, storage=blob.models.BlobFileSystemStorage(), upload_to=blob.models.blob_directory_path)),
                ('note', models.TextField(null=True)),
                ('date', models.TextField(null=True)),
                ('importance', models.IntegerField(default=1)),
                ('is_private', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='tag.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.Blob')),
            ],
        ),
        migrations.CreateModel(
            name='MetaDataNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.Document')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='metadatanew',
            unique_together=set([('name', 'value', 'blob')]),
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together=set([('name', 'value', 'blob')]),
        ),
    ]
