# Generated by Django 2.2.13 on 2020-10-30 22:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import blob.amazon
import blob.models


class Migration(migrations.Migration):

    replaces = [('blob', '0001_initial'), ('blob', '0002_auto_20200507_1818'), ('blob', '0003_auto_20200519_1821')]

    initial = True

    dependencies = [
        ('tag', '0006_tagalias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('sha1sum', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('file', models.FileField(blank=True, max_length=500, storage=blob.models.DownloadableS3Boto3Storage(), upload_to='')),
                ('note', models.TextField(null=True)),
                ('date', models.TextField(null=True)),
                ('importance', models.IntegerField(default=1)),
                ('is_private', models.BooleanField(default=False)),
                ('is_note', models.BooleanField(default=False)),
                ('documents', models.ManyToManyField('self', blank=True)),
                ('tags', models.ManyToManyField(to='tag.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(models.Model, blob.amazon.AmazonMixin),
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.Blob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'value', 'blob')},
            },
        ),
    ]
