# Generated by Django 2.0.13 on 2020-01-19 18:34

import blob.amazon
import blob.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0006_tagalias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('sha1sum', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('file', models.FileField(max_length=500, storage=blob.models.DownloadableS3Boto3Storage(), upload_to='')),
                ('note', models.TextField(null=True)),
                ('date', models.TextField(null=True)),
                ('importance', models.IntegerField(default=1)),
                ('is_private', models.BooleanField(default=False)),
                ('is_note', models.BooleanField(default=False)),
                ('documents', models.ManyToManyField(related_name='_document_documents_+', to='blob.Document')),
                ('tags', models.ManyToManyField(to='tag.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(models.Model, blob.amazon.AmazonMixin),
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('name', 'value', 'blob')},
        ),
    ]
