# Generated by Django 2.2.13 on 2021-04-16 00:40

import blob.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0013_auto_20210108_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('sha1sum', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('file', models.FileField(blank=True, max_length=500, storage=blob.models.DownloadableS3Boto3Storage(), upload_to='')),
                ('note', models.TextField(null=True)),
                ('date', models.TextField(null=True)),
                ('importance', models.IntegerField(default=1)),
                ('is_private', models.BooleanField(default=False)),
                ('is_note', models.BooleanField(default=False)),
                ('is_indexed', models.BooleanField(default=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='_blob_documents_+', to='blob.Blob')),
                ('tags', models.ManyToManyField(to='tag.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.Blob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'value', 'blob')},
            },
        ),
    ]
