# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='documents',
            field=models.ManyToManyField(related_name='_document_documents_+', to='blob.Document'),
        ),
    ]
