# Generated by Django 2.2.13 on 2020-11-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0001_squashed_0003_auto_20200519_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='_blob_documents_+', to='blob.Blob'),
        ),
    ]
