# Generated by Django 2.2.10 on 2020-05-07 22:18

import blob.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='_document_documents_+', to='blob.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=500, storage=blob.models.DownloadableS3Boto3Storage(), upload_to=''),
        ),
    ]
