# Generated by Django 2.0.7 on 2018-10-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='blob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.Document'),
        ),
    ]
