# Generated by Django 2.2.13 on 2021-02-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0002_auto_20201101_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='is_indexed',
            field=models.BooleanField(default=True),
        ),
    ]
