# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0002_document_documents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetaDataNew',
            new_name='MetaData',
        ),
    ]
