# Generated by Django 3.2.5 on 2021-07-16 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blob', '0002_auto_20210608_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blob',
            options={},
        ),
        migrations.AlterField(
            model_name='blob',
            name='sha1sum',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='blob',
            unique_together={('sha1sum', 'user')},
        ),
    ]
