# Generated by Django 2.2.10 on 2020-05-19 22:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import blob.amazon
import blob.models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0002_auto_20200507_1818'),
    ]

    operations = [
        migrations.RenameModel("Document", "Blob"),
    ]
