# Generated by Django 2.2.13 on 2021-04-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0003_blob_is_indexed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blob',
            old_name='title',
            new_name='name',
        ),
    ]
