# Generated by Django 2.0.7 on 2019-05-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0003_metadata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='is_blog',
            new_name='is_note',
        ),
    ]
