# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0003_auto_20170827_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blob',
            name='blobs',
        ),
        migrations.RemoveField(
            model_name='blob',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blob',
            name='user',
        ),
        migrations.AddField(
            model_name='document',
            name='is_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Blob',
        ),
    ]
