# Generated by Django 3.2.5 on 2021-10-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0003_auto_20210715_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='blob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='blob.blob'),
        ),
    ]
