# Generated by Django 2.0.13 on 2019-12-30 23:40

import blob.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0004_auto_20190512_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        )
    ]
