# Generated by Django 3.2.5 on 2021-11-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0004_alter_metadata_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='blobs',
            field=models.ManyToManyField(blank=True, related_name='_blob_blob_blobs_+', to='blob.Blob'),
        ),
    ]
