# Generated by Django 3.2.5 on 2021-12-01 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0005_blob_blobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blob',
            name='documents',
        ),
    ]
