# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0005_remove_blob_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='blobs',
            field=models.ManyToManyField(related_name='_blob_blobs_+', to='blob.Blob'),
        ),
    ]
