# Generated by Django 3.2.5 on 2021-12-11 00:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0006_remove_blob_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(default=1)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.blob')),
            ],
            options={
                'unique_together': {('blob', 'sort_order')},
            },
        ),
    ]
