# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0006_blob_blobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
