# Generated by Django 3.2.5 on 2022-01-08 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0009_auto_20210414_1951'),
        ('blob', '0007_recentlyviewedblob'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderBlobBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blob.blob')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark.bookmark')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('blob', 'bookmark')},
            },
        ),
        migrations.AddField(
            model_name='blob',
            name='bookmarks',
            field=models.ManyToManyField(through='blob.SortOrderBlobBookmark', to='bookmark.Bookmark'),
        ),
    ]
