# Generated by Django 3.2.5 on 2022-03-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0008_auto_20220108_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blob',
            name='is_private',
        ),
    ]
