# Generated by Django 3.2.5 on 2022-03-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0009_remove_blob_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='math_support',
            field=models.BooleanField(default=True),
        ),
    ]
