# Generated by Django 3.2.5 on 2022-03-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0010_blob_math_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='math_support',
            field=models.BooleanField(default=False),
        ),
    ]
