# Generated by Django 3.2.15 on 2022-09-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0011_alter_blob_math_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
