# Generated by Django 3.2.15 on 2022-09-13 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0012_blob_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlobBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('blob_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blob_1', to='blob.blob')),
                ('blob_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blob_2', to='blob.blob')),
            ],
            options={
                'unique_together': {('blob_1', 'blob_2')},
            },
        ),
        migrations.AddField(
            model_name='blob',
            name='blobs_new',
            field=models.ManyToManyField(through='blob.BlobBlob', to='blob.Blob'),
        ),
    ]
