# Generated by Django 3.2.15 on 2022-09-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0013_auto_20220913_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blob',
            name='blobs',
        ),
    ]
