# Generated by Django 3.2.15 on 2022-09-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0014_remove_blob_blobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blob',
            old_name='blobs_new',
            new_name='blobs',
        ),
    ]
