# Generated by Django 3.2.15 on 2022-09-15 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0015_rename_blobs_new_blob_blobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blobblob',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blobblob',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
