# Generated by Django 3.2.15 on 2022-10-13 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_bookmark_data'),
        ('drill', '0015_rename_sortorderdrillblob_sortorderquestionblob'),
        ('blob', '0016_auto_20220914_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('blob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blob.blob')),
                ('bookmark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmark.bookmark')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.question')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
