# Generated by Django 3.2.15 on 2022-10-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0017_bcobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcobject',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
