# Generated by Django 3.2.15 on 2022-10-14 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0018_bcobject_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcobject',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
