# Generated by Django 3.2.15 on 2022-10-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0019_bcobject_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcobject',
            name='question',
        ),
    ]
