# Generated by Django 3.2.18 on 2023-03-18 20:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_bookmark_data'),
        ('drill', '0021_auto_20221107_1700'),
        ('blob', '0020_remove_bcobject_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCObjectNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlobToObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('bc_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blob.bcobjectnew')),
                ('blob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blob.blob')),
                ('bookmark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmark.bookmark')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='blob.blob')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.question')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('node', 'blob', 'bookmark', 'question')},
            },
        ),
        migrations.AddField(
            model_name='blob',
            name='bc_objects',
            field=models.ManyToManyField(through='blob.BlobToObject', to='blob.BCObjectNew'),
        ),
    ]
