# Generated by Django 3.2.18 on 2023-03-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_bookmark_data'),
        ('drill', '0021_auto_20221107_1700'),
        ('blob', '0021_auto_20230318_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BCObject',
            new_name='BCQuestionObject',
        ),
    ]
