# Generated by Django 3.2.18 on 2023-03-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0022_rename_bcobject_bcquestionobject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BCObjectNew',
            new_name='BCObject',
        ),
    ]
