# Generated by Django 3.2.18 on 2023-03-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0023_rename_bcobjectnew_bcobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blob',
            name='blobs',
        ),
        migrations.RemoveField(
            model_name='blob',
            name='bookmarks',
        ),
        migrations.DeleteModel(
            name='BlobBlob',
        ),
    ]
