# Generated by Django 3.2.18 on 2023-03-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0024_auto_20230319_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SortOrderBlobBookmark',
        ),
    ]
