# Generated by Django 3.2.18 on 2023-03-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_bookmark_data'),
        ('drill', '0021_auto_20221107_1700'),
        ('blob', '0025_delete_sortorderblobbookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blobtoobject',
            unique_together={('node', 'question'), ('node', 'bookmark'), ('node', 'blob')},
        ),
    ]
