# Generated by Django 3.2.18 on 2023-04-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0026_alter_blobtoobject_unique_together'),
        ('drill', '0024_remove_question_bc_objects_old'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BCQuestionObject',
        ),
    ]
