# Generated by Django 3.2.19 on 2023-05-11 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0009_rename_sortordernodetodo_nodetodo'),
        ('blob', '0028_blobtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyviewedblob',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='node.node'),
        ),
        migrations.AlterField(
            model_name='recentlyviewedblob',
            name='blob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blob.blob'),
        ),
    ]
