# Generated by Django 3.2.19 on 2023-05-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0009_rename_sortordernodetodo_nodetodo'),
        ('blob', '0029_auto_20230511_1716'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recentlyviewedblob',
            unique_together={('blob', 'node')},
        ),
        migrations.RemoveField(
            model_name='recentlyviewedblob',
            name='sort_order',
        ),
    ]
