# Generated by Django 5.2.6 on 2025-09-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blob", "0030_auto_20230512_1747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blob",
            name="bc_objects",
            field=models.ManyToManyField(
                through="blob.BlobToObject",
                through_fields=("node", "bc_object"),
                to="blob.bcobject",
            ),
        ),
    ]
