# Generated by Django 3.2.25 on 2024-06-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210212_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='verify_ssl_certificate',
            field=models.BooleanField(default=True),
        ),
    ]
