from django.urls import path

from . import views

app_name = "node"

urlpatterns = [
    path(
        route="",
        view=views.NodeListView.as_view(),
        name="list"
    ),
    path(
        route="<uuid:uuid>/",
        view=views.NodeDetailView.as_view(),
        name="detail"
    ),
    path(
        route="create/",
        view=views.NodeCreateView.as_view(),
        name="create"
    ),
    path(
        route="<uuid:uuid>/todo_list/",
        view=views.get_todo_list,
        name="get_todo_list"
    ),
    path(
        route="edit_note/",
        view=views.edit_note,
        name="edit_note"
    ),
    path(
        route="todo/add/",
        view=views.add_todo,
        name="add_todo"
    ),
    path(
        route="todo/remove/",
        view=views.remove_todo,
        name="remove_todo"
    ),
    path(
        route="todo/sort/",
        view=views.sort_todos,
        name="sort_todos"
    ),
    path(
        route="change_layout",
        view=views.change_layout,
        name="change_layout"
    ),
    path(
        route="collection/add",
        view=views.add_collection,
        name="add_collection"
    ),
    path(
        route="collection/delete",
        view=views.delete_collection,
        name="delete_collection"
    ),
    path(
        route="note/add",
        view=views.add_note,
        name="add_note"
    ),
    path(
        route="note/delete",
        view=views.delete_note,
        name="delete_note"
    ),
    path(
        route="note/color",
        view=views.set_note_color,
        name="set_note_color"
    ),
    path(
        route="image/remove",
        view=views.remove_image,
        name="remove_image"
    )
]
