# This is an "untested" WIP Cloudformation template. The actual
#  Bordercore S3 buckets were created using the AWS console UI,
#  but in theory future buckets should be created using something
#  like this.

AWSTemplateFormatVersion: '2010-09-09'
Description: Example Stack

Parameters:
  BucketName:
    Type: String
    Default: bordercore-test
  TopicName:
    Type: String
    Default: NewS3Blob

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

      NotificationConfiguration:
        TopicConfigurations:
          - Event: 's3:ObjectCreated:*'
            # Name: NewS3BlobEvent
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: blobs/
            Topic: 'arn:aws:sns:us-east-1:192218769908:NewS3Blob'

      Policies:
      - PolicyName: PublishToSNS
        PolicyDocument:
          Statement:
            - Effect: 'Allow'
              Principal:
                Service: 's3.amazonaws.com'
              Action:
                - sns:Publish
              Resource:
                - '*'
                # "Condition": {
                #   "ArnLike": { "aws:SourceArn": "arn:aws:s3:*:*:bucket-name" }
                #   }
