# Generated by Django 2.0.7 on 2018-09-23 21:10

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, null=True)),
                ('middle_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('preferred_name', models.CharField(blank=True, choices=[('first_name', 'First Name'), ('middle_name', 'Middle Name'), ('last_name', 'Last Name')], default='first_name', max_length=20)),
                ('mobile_number', models.TextField(blank=True, null=True)),
                ('work_number', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('address_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('im', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
