# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='preferred_name',
            field=models.CharField(blank=True, choices=[('First Name', 'first_name'), ('Middle Name', 'middle_name'), ('Last Name', 'last_name')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
