# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20180415_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='preferred_name',
            field=models.CharField(blank=True, choices=[('First Name', 'first_name'), ('Middle Name', 'middle_name'), ('Last Name', 'last_name')], default='first_name', max_length=20),
        ),
    ]
