# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180415_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='preferred_name',
            field=models.CharField(blank=True, choices=[('first_name', 'First Name'), ('middle_name', 'Middle Name'), ('last_name', 'Last Name')], default='first_name', max_length=20),
        ),
    ]
