# Generated by Django 2.2.10 on 2020-04-07 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseuser',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
