# Generated by Django 2.2.10 on 2020-04-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_exerciseuser_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseuser',
            name='frequency',
        ),
    ]
