# Generated by Django 2.2.13 on 2020-08-29 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_remove_exerciseuser_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseuser',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
