# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20160214_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
