# Generated by Django 2.2.13 on 2021-04-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_exercise_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='muscle',
            old_name='muscle',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='musclegroup',
            old_name='muscle_group',
            new_name='name',
        ),
    ]
