# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_auto_20160821_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseuser',
            name='frequency',
            field=models.IntegerField(default=7),
        ),
    ]
