# Generated by Django 3.2.5 on 2022-01-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_auto_20210415_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderExerciseMuscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('theme', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary', max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.muscle')),
            ],
            options={
                'unique_together': {('exercise', 'muscle')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_new',
            field=models.ManyToManyField(related_name='muscle', through='fitness.SortOrderExerciseMuscle', to='fitness.Muscle'),
        ),
    ]
