# Generated by Django 3.2.5 on 2022-01-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_auto_20220124_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
