# Generated by Django 3.2.5 on 2022-02-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_auto_20220203_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='exercise',
        ),
    ]
