# Generated by Django 3.2.5 on 2022-02-06 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_remove_data_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.workout'),
        ),
    ]
