# Generated by Django 3.2.5 on 2022-02-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_alter_data_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
    ]
