# Generated by Django 3.2.5 on 2022-02-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_remove_data_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortorderexercisemuscle',
            old_name='theme',
            new_name='target',
        ),
    ]
