# Generated by Django 3.2.5 on 2022-02-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_rename_theme_sortorderexercisemuscle_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscle',
        ),
    ]
