# Generated by Django 3.2.5 on 2022-02-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_remove_exercise_muscle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='muscle_new',
            new_name='muscle',
        ),
    ]
