# Generated by Django 3.2.5 on 2022-02-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_rename_muscle_new_exercise_muscle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseuser',
            old_name='interval',
            new_name='frequency',
        ),
    ]
