# Generated by Django 3.2.14 on 2022-08-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_rename_interval_exerciseuser_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseuser',
            name='rest_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
