# Generated by Django 3.2.15 on 2022-10-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_exerciseuser_rest_period'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortOrderExerciseMuscle',
            new_name='ExerciseMuscle',
        ),
    ]
