# Generated by Django 3.2.17 on 2023-02-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_rename_sortorderexercisemuscle_exercisemuscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseuser',
            name='rest_period',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
