# Generated by Django 3.2.21 on 2023-11-01 23:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0019_alter_exerciseuser_rest_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseuser',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[1, 0, 0, 0, 0, 0, 0], size=7),
            preserve_default=False,
        ),
    ]
