# Generated by Django 3.2.21 on 2023-11-01 23:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0020_exerciseuser_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseuser',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(blank=True, null=True), size=7),
        ),
    ]
