# Generated by Django 3.2.23 on 2024-01-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0021_alter_exerciseuser_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='has_duration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='has_weight',
            field=models.BooleanField(default=True),
        ),
    ]
