# Generated by Django 4.2.22 on 2025-07-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0022_auto_20240119_1446"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="muscle",
            options={"ordering": ["name"]},
        ),
    ]
