# Generated by Django 4.2.22 on 2025-09-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0023_alter_exercise_options_alter_muscle_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="reps",
            field=models.PositiveIntegerField(),
        ),
    ]
