# Generated by Django 2.0.7 on 2019-03-17 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark', '0002_auto_20190218_1824'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TagBookmarkSortOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField()),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark.Bookmark')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.TagBookmark')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='tagbookmark',
            name='bookmarks',
            field=models.ManyToManyField(through='tag.TagBookmarkSortOrder', to='bookmark.Bookmark'),
        ),
        migrations.AddField(
            model_name='tagbookmark',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='tagbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tagbookmarksortorder',
            unique_together={('tag', 'bookmark')},
        ),
    ]
