# Generated by Django 2.0.7 on 2019-03-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20190218_1824'),
        ('tag', '0002_auto_20190317_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagbookmarksortorder',
            old_name='tag',
            new_name='tag_bookmark',
        ),
        migrations.AlterUniqueTogether(
            name='tagbookmarksortorder',
            unique_together={('tag_bookmark', 'bookmark')},
        ),
    ]
