# Generated by Django 2.0.7 on 2019-03-18 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_auto_20190317_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagbookmark',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tag.Tag', unique=True),
        ),
    ]
