# Generated by Django 2.0.13 on 2020-01-02 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_auto_20190317_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagbookmark',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tag.Tag'),
        ),
    ]
