# Generated by Django 2.2.13 on 2020-08-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0006_tagalias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagalias',
            options={'verbose_name_plural': 'Tag Aliases'},
        ),
    ]
