# Generated by Django 2.2.13 on 2020-10-26 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0007_auto_20200829_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderTagTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Todo')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('tag', 'todo')},
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='todos',
            field=models.ManyToManyField(through='tag.SortOrderTagTodo', to='todo.Todo'),
        ),
    ]
