# Generated by Django 2.2.13 on 2020-10-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20190331_2024'),
        ('tag', '0008_auto_20201026_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOrderTagBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark.Bookmark')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('tag', 'bookmark')},
            },
        ),
    ]
