# Generated by Django 2.2.13 on 2020-10-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20190331_2024'),
        ('tag', '0009_sortordertagbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='bookmarks',
            field=models.ManyToManyField(through='tag.SortOrderTagBookmark', to='bookmark.Bookmark'),
        ),
    ]
