# Generated by Django 2.2.13 on 2020-10-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0010_tag_bookmarks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagbookmarksortorder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tagbookmarksortorder',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='tagbookmarksortorder',
            name='tag_bookmark',
        ),
        migrations.DeleteModel(
            name='TagBookmark',
        ),
        migrations.DeleteModel(
            name='TagBookmarkSortOrder',
        ),
    ]
