# Generated by Django 3.2.5 on 2021-10-27 21:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0013_auto_20210108_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagalias',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
