# Generated by Django 3.2.5 on 2022-05-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0014_tagalias_uuid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(check=models.Q(('name__contains', ','), _negated=True), name='check_no_commas'),
        ),
    ]
