# Generated by Django 3.2.15 on 2022-10-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_bookmark_data'),
        ('tag', '0015_tag_check_no_commas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortOrderTagBookmark',
            new_name='TagBookmark',
        ),
    ]
