# Generated by Django 3.2.15 on 2022-10-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_todo_priority'),
        ('tag', '0016_rename_sortordertagbookmark_tagbookmark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortOrderTagTodo',
            new_name='TagTodo',
        ),
    ]
