# Generated by Django 3.2.18 on 2023-03-10 19:51

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0017_rename_sortordertagtodo_tagtodo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Lower('name'))), name='check_name_is_lowercase'),
        ),
    ]
