# Generated by Django 5.2.6 on 2025-10-02 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_bookmark_data'),
        ('tag', '0018_tag_check_name_is_lowercase'),
        ('todo', '0015_alter_todo_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tagbookmark',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tagtodo',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='uniq_tag_name_user'),
        ),
        migrations.AddConstraint(
            model_name='tagbookmark',
            constraint=models.UniqueConstraint(fields=('tag', 'bookmark'), name='uniq_tag_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='tagtodo',
            constraint=models.UniqueConstraint(fields=('tag', 'todo'), name='uniq_tag_todo'),
        ),
    ]
