name: Run Pytest

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: $PYTHONPATH:.:bordercore
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements/dev.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest bin/
