# Generated by Django 3.2.5 on 2022-02-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listen',
        ),
    ]
