# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_time_played',
            field=models.DateTimeField(null=True),
        ),
    ]
