# Generated by Django 2.0.13 on 2020-01-02 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181014_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
