# Generated by Django 3.2.14 on 2022-07-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_delete_listen'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
