# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_last_time_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='original_release_year',
            field=models.IntegerField(null=True),
        ),
    ]
