# Generated by Django 2.2.9 on 2020-02-09 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
    ]
