# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_original_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='times_played',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
