# Generated by Django 2.2.13 on 2020-08-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200209_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
