# Generated by Django 2.2.13 on 2021-02-05 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
