# Generated by Django 2.2.13 on 2021-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='comment',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='album',
            name='comment',
        ),
        migrations.AddField(
            model_name='album',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
