# Generated by Django 4.2.21 on 2025-05-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_listen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="type",
            field=models.CharField(
                choices=[("manual", "Manually Selected"), ("smart", "Smart")],
                default="manual",
                max_length=100,
            ),
        ),
    ]
