# Generated by Django 4.2.22 on 2025-08-30 22:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music", "0007_alter_playlist_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="times_played",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="song",
            name="track",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="album",
            unique_together={("title", "artist", "user")},
        ),
    ]
