# Generated by Django 2.2.22 on 2021-06-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_playlist_playlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='title',
            new_name='name',
        ),
    ]
