# Generated by Django 4.2.22 on 2025-09-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0008_alter_song_rating_alter_song_times_played_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
