# Generated by Django 2.2.22 on 2021-06-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20210608_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
    ]
