# Generated by Django 2.2.22 on 2021-06-13 00:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20210609_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_type',
            field=models.TextField(default='manual'),
        ),
    ]
