# Generated by Django 3.2.4 on 2021-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20210612_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_type',
            field=models.CharField(choices=[('manual', 'Manually Selected'), ('tag', 'Tagged'), ('recent', 'Recently Added'), ('time', 'Time Period'), ('rating', 'Rated')], default='manual', max_length=100),
        ),
    ]
