# Generated by Django 3.2.4 on 2021-06-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20210613_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_parameters',
            new_name='parameters',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_size',
            new_name='size',
        ),
    ]
