# Generated by Django 3.2.4 on 2021-06-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20210614_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_type',
            new_name='type',
        ),
    ]
