# Generated by Django 3.2.4 on 2021-06-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_rename_playlist_type_playlist_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('playlist', 'song')},
        ),
    ]
