# Generated by Django 3.2.4 on 2021-06-17 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20210617_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song'),
        ),
    ]
