# Generated by Django 3.2.5 on 2021-07-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0013_auto_20210108_1637'),
        ('music', '0016_auto_20210617_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
